PAY-2354 Primary-key on calculations table in pay-statement-data shou…
DEFRA/ffc-pay-statement-data pull request #6
Opened 2022-09-19 22:40 UTC by AbidemiAdio

…ld be combination of calculationId and scheme

2022-09-20 09:07 UTC, marctemp commented
Does this change the data we are expecting to arrive into our service via ServiceBus, i.e. do we need to update our `asyncapi.yaml` to say tht SBI/FRN are string not number?

2022-10-03 10:33 UTC, AbidemiAdio commented
> Does this change the data we are expecting to arrive into our service via ServiceBus, i.e. do we need to update our `asyncapi.yaml` to say tht SBI/FRN are string not number?
> 
> Also, does this mean we want to convert our `integer`/`bigint` data types for these too?

We are not changing data-type, neither are we changing content of data we are expecting to arrive into our service, DWH has agreed to fix all the gaps identified.

2022-10-03 10:42 UTC, marctemp commented on changelog/db.changelog-1.3.xml
> +    <dropForeignKeyConstraint  baseTableName="fundings" constraintName="fk_calculations_calculationId"/>
We need to add back our new FK link

2022-10-03 10:42 UTC, marctemp requested changes
Update the diagram ERD: https://github.com/DEFRA/ffc-diagrams/blob/main/Payments/ffc-pay-statement-db-schema.drawio

2022-10-03 11:56 UTC, AbidemiAdio commented
> Update the diagram ERD: https://github.com/DEFRA/ffc-diagrams/blob/main/Payments/ffc-pay-statement-db-schema.drawio

ERD updated, here is the link to pull request : https://github.com/DEFRA/ffc-diagrams/pull/5

2022-10-03 13:15 UTC, marctemp approved these changes
LGTM

2022-10-03 16:16 UTC, merged